### ISSUE TITLE
Chain mismatch , KeyError: 'A'

### ISSUE THREAD

**Issue by nonononanana** [bjornwallner/DockQ#12]
Hi, I found  "chain mismatch" problem in almost all complexes I tested.
I've been stuck for days. I would very much appreciate it if anyone help me out.

After I ran ./DockQ.py model/7P79.pdb native/7P79.pdb, it showed:
> 7P79.pdb
> chain mismatch A B H Cchain mismatch A B H CTraceback (most recent call last):
>   File "./DockQ.py", line 732, in <module>
>     main()    
>   File "./DockQ.py", line 660, in main
>     info=calc_DockQ(model,native,use_CA_only=use_CA_only,capri_peptide=capri_peptide) #False):
>   File "./DockQ.py", line 234, in calc_DockQ
>     if key in chain_res[chain]: # if key is present in sample
> KeyError: 'A'

Any tips for fixing this?
Thank you so much.

**Comment by EdgarAraya** [comment]
Hi, did you manage to solve this?

**Comment by nonononanana** [comment]
> Hi, did you manage to solve this?

Hey, yes. Just rename the chains to keep them aligned.

**Comment by EdgarAraya** [comment]
Thanks! That worked.
