### ISSUE TITLE
How to align chain ID of two complexes before running DockQ?

### ISSUE THREAD

**Issue by nonononanana** [bjornwallner/DockQ#13]
I am writing a python script to rename chain ID in model file and confronted with a lot of problems. 
I was wondering how do people align chain IDs before running DockQ? Is there any tool?

**Comment by ulupo** [comment]
Perhaps [pdb-tools](http://www.bonvinlab.org/pdb-tools/) might help?  Particularly the commands `pdb_chainbows` and `pdb_rplchain`.
