### ISSUE TITLE
Script fixnumbering.pl does not output model.pdb.fixed

### ISSUE THREAD

**Issue by JasperGeissler** [bjornwallner/DockQ#17]
Hi,

Thank you for developing this useful software. When I attempt to run the script to align the protein lengths of the separate chains of the predicted model, I am met with the error that needle is not installed. However, when I run the script without any input, it says needle is in fact installed. How do I circumvent this?

Thanks in advance.

**Comment by nemo8130** [comment]
To check if needle is installed and running, type 'needle' and enter from
any terminal. If it is installed and working, you should be prompted the
following:

***@***.***:~$ *needle*
Needleman-Wunsch global alignment of two sequences
Input sequence:

Best,
Sankar

**Comment by JasperGeissler** [comment]
> 

Thank you for your reply.

I have tried this already, and verified that needle is installed and available from the command line. Using the command 'which needle' I have also verified that needle is available from the command line. Invoking the script fix_numbering.pl without any inputs provides an extra confirmation by returning "needle found to be installed in the path". This message changes to "needle NOT found in the path" upon removal of emboss, so needle is most definitely there. 

My issue pertains to the script somehow not being able to detect needle when I invoke the script with the predicted and native .pdb files as per your documentation (by using scripts/fix_numbering.pl model.pdb native.pdb with DockQ as my working directory). I was wondering if you have a solution for this unexpected behaviour.

**Comment by nemo8130** [comment]
It would be best if Prof. Wallner replies to this - as he long maintains
it. I still use an older GitHub version, which runs fine for me. And, one
has to use fix_numbering.pl for making the two input files continuous in
sequence.

***@***.***:~/Desktop/my_softwares/DockQ$ ./DockQ.exe
EXAMPLE_PDBS/model_fixed.pdb EXAMPLE_PDBS/native_fixed.pdb
 *********************************************************
 *                       DockQ                           *
 *   Scoring function for protein-protein docking models *
 *   Statistics on CAPRI data:                           *
 *    0    <  DockQ <  0.23 - Incorrect                  *
 *    0.23 <= DockQ <  0.49 - Acceptable quality         *
 *    0.40 <= DockQ <  0.79 - Medium quality             *
 *            DockQ >= 0.79 - High quality               *
 *   Reference: Sankar Basu and Bjorn Wallner, DockQ:... *
 *   For comments, please email: ***@***.***       *
 *********************************************************
    fnat:    0.589:   33      correct out of   56     native contacts
  fnonat:    0.459:   28   non-native out of   61      model contacts
  0.5218419
 Medium
Fnat=   0.589  LRMS_bb=       6.985  IRMS=       1.919  DockQ=     0.52184
CAPRI_class (DockQ): Medium

I haven't needed to use it lately.

Best,
Sankar

**Comment by JasperGeissler** [comment]
I have e-mailed professor Wallner as well earlier, and he unfortunately hasn't had opportunity to reply yet. 

Have you and prof. Wallner maintained contact? Do you think it would be possible then for you to reach out to him as well? I hope that is not too tall an order.

Thank you for the help.

**Comment by bjornwallner** [comment]
Strange.
A quick fix would be to remove the check for location of needle in the fix numbering script and hard code the full path when calling needle

We are working on an update in which does not require any additional scripts. It wil be out in the next couple of weeks.

Cheers
Björn

On 10 Mar 2023, at 16:40, JasperGeissler ***@***.***> wrote:

﻿

I have e-mailed professor Wallner as well earlier, and he unfortunately hasn't had opportunity to reply yet.

Have you and prof. Wallner maintained contact? Do you think it would be possible then for you to reach out to him as well? I hope that is not too tall an order.

Thank you for the help.

**Comment by JasperGeissler** [comment]
Hi, the issue appears to have been solved. There was a bug on my end. Thank you for the troubleshooting and the development of this useful software.

**Comment by nemo8130** [comment]
👍

**Comment by rocke2020** [comment]
> Strange. A quick fix would be to remove the check for location of needle in the fix numbering script and hard code the full path when calling needle We are working on an update in which does not require any additional scripts. It wil be out in the next couple of weeks. Cheers Björn On 10 Mar 2023, at 16:40, JasperGeissler ***@***.***> wrote: ﻿ I have e-mailed professor Wallner as well earlier, and he unfortunately hasn't had opportunity to reply yet. Have you and prof. Wallner maintained contact? Do you think it would be possible then for you to reach out to him as well? I hope that is not too tall an order. Thank you for the help. — Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbjornwallner%2FDockQ%2Fissues%2F17%23issuecomment-1463983733&data=05%7C01%7Cbjorn.wallner%40liu.se%7C1aa4f5a6072942414e9908db217dbcf7%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C638140596142095734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=egj5STG4HMIrskHM32W%2FBihWwXe3D2FS%2FwvkSC87EMM%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABAG3YDBL6JA7W3XCZK3O23W3NDNVANCNFSM6AAAAAAVWMIYTE&data=05%7C01%7Cbjorn.wallner%40liu.se%7C1aa4f5a6072942414e9908db217dbcf7%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C638140596142095734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8NFnFFz4e1EwwywPip9o96UqoaOEU3yzNsPIggvuaKY%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I also have problem to install the 2013/2012 year EMBOSS-6 and cannot find needle at all.
Sincerely waiting for a new version without dependent on EMBOSS.
thanks!!

**Comment by rocke2020** [comment]
@nemo8130  "We are working on an update in which does not require any additional scripts. It wil be out in the next couple of weeks."
I see the Dock Q from many CAPRI papers, an excellent contribution for us. 
It is quite hard to me to write a CAPRI metrics, especially i-rmsd(it need pre align and then calculcate interface area), fnat, and now I do need a continuous docking quality score.
If you can update Dock Q without these additon scripts, it will be very good helpful to us. 
thanks!!!
