### ISSUE TITLE
cannot install emboss and cannot find "which needle"

### ISSUE THREAD

**Issue by rocke2020** [bjornwallner/DockQ#18]
Dear @bjornwallner 

My system is ubuntu 20.04
From https://emboss.sourceforge.net/download/, I install stable version [EMBOSS-6.5.7.tar.gz](ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.5.7.tar.gz)
which was released in  2012/2013 according to the change log
https://emboss.sourceforge.net/developers/changelog.html.
After installation of emboss(I guess it failed), I cannot find "needle" by "which needle"?

thanks very much.

**Comment by yxnyu** [comment]
I had the same issue
