### ISSUE TITLE
Bug in aligning model to native (cython branch)

### ISSUE THREAD

**Issue by alirezaomidi** [bjornwallner/DockQ#21]
In `cython` branch, an instance of `Align.PairwiseAligner` is created, configured, but not used:
https://github.com/bjornwallner/DockQ/blob/01f97033ffee5a3e335e8f9bc1032676056a8288/src/DockQ/DockQ.py#L305-L310

Also, extracting the alignment is not accurate here:
https://github.com/bjornwallner/DockQ/blob/01f97033ffee5a3e335e8f9bc1032676056a8288/src/DockQ/DockQ.py#L311-L312
and should be:
```python
alignment['seqA'] = aln[0, :]
alignment['seqB'] = aln[1, :]
```

**Comment by clami66** [comment]
Hi alireza,

Thanks for pointing the issue with the aligner! About the formatting issue, that was the correct way of doing it in older biopython versions (<1.79, I think). When the next version is released we will update the biopython requirements and fix this issue.
