### ISSUE TITLE
Pip Install Issue

### ISSUE THREAD

**Issue by EureKaZhu** [bjornwallner/DockQ#27]
Why the code will report error like:
```
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from DockQ.DockQ import load_PDB, run_on_all_native_interfaces
ModuleNotFoundError: No module named 'DockQ'
```
After I use the `pip install .` 
How can I fix it?
Thank for your response

**Comment by clami66** [comment]
I am not sure where the file `a.py` comes from. Is this something you created?

**Comment by clami66** [comment]
@EureKaZhu I am closing this issue for now since you haven't responded. Feel free to reopen if needed
