### ISSUE TITLE
np.dot(ligand_atoms_sample, rot) error.

### ISSUE THREAD

**Issue by luwei0917** [bjornwallner/DockQ#29]
Hello,
Most of my cases run smoothly, but I tried 'DockQ  B.cif  A.pdb', this give me error,
rotated_sample_atoms = np.dot(ligand_atoms_sample, rot) + tran
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (0,) and (3,3) not aligned: 0 (dim 0) != 3 (dim 0)

[case.zip](https://github.com/bjornwallner/DockQ/files/15319698/case.zip)

Do you know why? Thanks.

**Comment by clami66** [comment]
Hi,

At the bottom of `A.pdb` you have small molecules marked as `ATOM` records.

```
ATOM   7396  MG   MG     1      42.919  43.434  79.010  1.00 67.80           M  
ATOM   7397  PG  GTP C   2      42.759  40.202  78.638  1.00 41.72           P  
ATOM   7398  O1G GTP C   2      43.055  38.964  79.589  1.00 41.38           O  
...
```

Delete those or mark them as `HETATM` instead, and the issue should be fixed
