### ISSUE TITLE
Can two slightly different （length）sequence be allplied to DockQ algorithm?

### ISSUE THREAD

**Issue by Ming-Qin-tech** [bjornwallner/DockQ#30]

**Comment by Ming-Qin-tech** [comment]
In Flexible docking cases, a same protein pdbid can have slightly different before and after this flexible docking.
For example, If I extract the protein sequence from "1a2k_receptor_unbound.pdb", the chain A's sequence is :"GDKPIWEQIGSSFIQHYYQLFDNDRTQLGAIYIDASCLTWEGQQFQGKAAIVEKLSSLPFQKIQHSITAQDHQPTPDSCIISMVVGQLKADEDPIMGFHQMFLLKNINDAWVCTNDMFRLALHNF"

However, the sequence from "1a2k_receptor_bound.pdb" is :
"KPIWEQIGSSFIQHYYQLFDNDRTQLGAIYIDASCLTWEGQQFQGKAAIVEKLSSLPFQKIQHSITAQDHQPTPDSCIISMVVGQLKADEDPIMGFHQMFLLKNINDAWVCTNDMFRLALHNFG".

we can see the different of the sequence length. To evaluate the felxible docking model performance, I want to run DockQ algprithm to evaluate the two pdb file. The question is: can Can two slightly different （length）sequence be allplied to DockQ algorithm?

**Comment by Ming-Qin-tech** [comment]
If cannot use it, what strategy your suggested to cut the sequence to maintain the same length? now I am trying sequence align algorithm to cut the longer sequence.

**Comment by clami66** [comment]
Hi, if I understand correctly your question then yes, DockQ realigns the sequences and only performs comparisons on the parts that are in both the model and the reference structures
