### ISSUE TITLE
Python/pip version

### ISSUE THREAD

**Issue by Luke-ebbis** [bjornwallner/DockQ#32]
Hey developers of DockQ, when I attempt to install the software I get the error:

```
pip install .
Processing /home/sibbe/Downloads/DockQ
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
ERROR: Package 'dockq-2.1' requires a different Python: 3.8.10 not in '>=3.9'
```

I am using pip 24.0 and python 3.8.10. 

From just checking the documentation, it is not clear which version of python you used to build the project. Could you help me?

Kind regards

**Comment by clami66** [comment]
Hi,

python >= 3.9 is required to install DockQ, as we haven't tested it on older versions. If you cannot update python, you could try and set the requirement in [project.toml](https://github.com/bjornwallner/DockQ/blob/5473f03ed7f757442187eec6fc48a0416937f311/pyproject.toml#L14) to python 3.8 and rerun pip install, but I can't guarantee that it will work.

**Comment by Luke-ebbis** [comment]
Thank you, I found that also having the correct pip version is important.

```
python = "3.9.1"
pip = ">=24.0,<25"
```

this worked to assemble the project.
