### ISSUE TITLE
CIFs don't seem to work properly

### ISSUE THREAD

**Issue by nzrandol** [bjornwallner/DockQ#34]
Hello! I've noticed that CIF files don't seem to work properly with DockQ. I've been using DockQ as a Python module and when I give a structure from a PDB file to `run_on_all_native_interfaces` as both the model and native, it works as expected (a perfect score). But when I try this same test with the same structure but in a CIF format, the scores are drastically different.

Here's a screenshot of what I've tried:
<img width="710" alt="Screenshot 2024-06-13 at 9 53 58 AM" src="https://github.com/bjornwallner/DockQ/assets/74268436/ab189be5-8c84-4df6-9ad0-1149aa7d48a3">

**Comment by clami66** [comment]
Hi, it's a bit hard to say what's going on just from the screenshot. Can you attach the CIF files perhaps?

**Comment by nzrandol** [comment]
I've done a little bit more playing around with this, and I think the issue is a bit more complicated than "CIFs don't work". I've attached a zip file that contains the files I'm using a test Python script. 

When I run the script, the "N-N CIF" and "D-N CIF" outputs are identical and match the "N-N PDB" results. Interestingly if you swap the two lines around (so "D-N CIF" before "N-N CIF"), the outputs are still identical but now match the "D-N PDB" results.

When using the command line, it seems to be fine. So this seems to me like some sort of Python memory issue related to CIFs?

[dockQ_test.zip](https://github.com/user-attachments/files/15827728/dockQ_test.zip)

**Comment by clami66** [comment]
This is probably related to issue #26
After loading a PDB try to follow it up with, e.g.:
`native1.id = "1kee_native.cif"`

So that every structure has a different `id` field. That should help with avoiding problems with the lru_cache.

I will push a fix to this as soon as possible

**Comment by clami66** [comment]
@nzrandol this should be fixed now, please try to pull the latest commit and check again

You were right that this was a CIF issue, as I had fixed this following #26 but only for `.pdb` files somehow
