### ISSUE TITLE
Parser.py has some issues

### ISSUE THREAD

**Issue by jaideepm009** [bjornwallner/DockQ#36]
[
<img width="1171" alt="Screenshot 2024-06-14 at 12 30 15 PM" src="https://github.com/bjornwallner/DockQ/assets/170813891/430b0f84-5301-4ec7-ab45-c527d570379b">
](url)

I believe "r" should be replaced with "current_resname" in line 452 of parser.py file under DockQ directory?

**Comment by jaideepm009** [comment]
But if i make the above change I get "Buffer has wrong number of dimensions (expected 2, got 1)". So I am not sure whats the issue.

**Comment by clami66** [comment]
Hi, could you attach the files you're trying to score?

**Comment by jaideepm009** [comment]
Here the files I am trying to process is 1cbv.pdb and the model file produced by rosettafold2 architecture. I am not able to attach them here :(

**Comment by clami66** [comment]
Try this:
1. Update the repository with `git pull` and rerun `pip install`
2. Since 1cbv contains a very small DNA molecule, it's likely that the short sequence is messing with the automatic mapping. So try to provide the mapping between native and model chains manually. It will be something like: `--mapping DHL:ABC` or similar (depends in what order Rosetta writes out the chains)

**Comment by jaideepm009** [comment]
I was providing chain map manually. I did git pull and reinstalled DockQ. I am still getting error in buffer dimension. Here are the screenshots of my code. 
![Screenshot 2024-06-17 at 9 11 49 AM](https://github.com/bjornwallner/DockQ/assets/170813891/803decaf-4bc3-43f9-9e17-81cc5b93f7eb)
![Screenshot 2024-06-17 at 9 12 39 AM](https://github.com/bjornwallner/DockQ/assets/170813891/a2c29fdb-646a-48fa-b4f5-94e5e912a933)

**Comment by clami66** [comment]
I cannot help you further without the model unfortunately. You should be able to make a zip, then drag and drop it in a comment box here on the issue

**Comment by jaideepm009** [comment]
[Archive.zip](https://github.com/user-attachments/files/15873379/Archive.zip)

In model(model_00_pred.pdb): A corresponds to antigen chain, B corresponds to heavy chain, C corresponds to light chain. In native("1cbv.pdb): D = antigen, H = heavy, L = light. I need to calculate DockQ for antigen to heavy and antigen to  light chains

**Comment by clami66** [comment]
Hi @jaideepm009 

Chain A in your model is a peptide with unknown amino acids:

```
ATOM      1  N   UNK A   1     -14.695   1.700   8.805  1.00 33.72
ATOM      2  CA  UNK A   1     -16.016   2.020   8.281  1.00 33.72
ATOM      3  C   UNK A   1     -17.109   1.521   9.211  1.00 33.72
ATOM      4  O   UNK A   1     -17.328   0.316   9.344  1.00 33.72
ATOM      5  CB  UNK A   1     -16.594   1.112   7.207  1.00 33.72
ATOM      6  H   UNK A   1     -14.203   0.899   8.438  1.00 33.72
ATOM      7  HA  UNK A   1     -16.094   3.104   8.211  1.00 33.72
ATOM      8 1HB  UNK A   1     -17.641   1.395   7.016  1.00 33.72
ATOM      9 2HB  UNK A   1     -16.016   1.213   6.289  1.00 33.72
ATOM     10 3HB  UNK A   1     -16.562   0.078   7.547  1.00 33.72
```

But the native chain D is a NA (DNA?) molecule. So there is no way for DockQ to compare the two. The type of molecules need to be consistent across the two pdb files or it doesn't make sense to compare them
