### ISSUE TITLE
Docking of single chain structures

### ISSUE THREAD

**Issue by HsinChinLi** [bjornwallner/DockQ#44]
Thanks for making DockQ public!
I am working on single-chain structures and failed on docking attempt due to "Need at least two chains in the two inputs"
Is there a way to perform single chain docking among two structures?

**Comment by HsinChinLi** [comment]
Thanks for the reply. It's two separated files of an antibody and an antigen that I extracted from a complex PDB structure. Both are single-chain PDB file. I'm not familiar with DockQ, does my approach plausible or it does not fit with the DockQ mechanism?

**Comment by clami66** [comment]
DockQ is not a software to perform docking.

It is only meant to evaluate the quality of a docked model compared to a reference. In your example, once you have docked your antibody/antigen complex with some other software (AlphaFold, HADDOCK...), you should get a single PDB files containing two chains (antigen chain and antibody chain in the same PDB).

Once you have that, then you can use DockQ to compare your docked structure against an experimental structure of the same complex.
