### ISSUE TITLE
Potential Issues with Sequence Parsing

### ISSUE THREAD

**Issue by wtni-gidle** [bjornwallner/DockQ#47]
When scoring the interactions between proteins and nucleic acids, I noticed that the parsed sequence might have issues. The following code is from https://github.com/bjornwallner/DockQ/blob/master/src/DockQ/parsers.py#L431
```
if hetatm_flag == " ":
    resname1 = (
        seq1(current_resname, custom_map=custom_map)
        if len(current_resname) == 3
        else current_resname[:-1]
        if (len(current_resname) == 2)
        else current_resname
    )
```
If the residue is DNA, like “DA“, it will produce "D" rather than "A". 
Another question is that I haven't found any code distinguishing the molecular type of sequences. Does this mean that during mapping, the protein chain of native might align with the nucleic acid chain of model?

**Comment by clami66** [comment]
Hello, you are right, thanks for letting us know. We have fixed this in your latest commit.

> I haven't found any code distinguishing the molecular type of sequences. Does this mean that during mapping, the protein chain of native might align with the nucleic acid chain of model?

The aligner wants the sequences to match perfectly, so it should never become an issue, unless a protein and NA in the same model happen to have identical sequences!
