### ISSUE TITLE
AssertionError: Zero number of equivalent atoms in native and model ligand (chain B) 0 0.

### ISSUE THREAD

**Issue by daniel1991zy** [bjornwallner/DockQ#5]
when I run the DockQ, it showed the error "AssertionError: Zero number of equivalent atoms in native and model ligand (chain B) 0 0.  Check that the residue numbers in model and native is consistent." And I used the fix_numbering.pl tool to produce the model.pdb.fixed file. However, How did I use the file to fix the error?

**Comment by hyeh20** [comment]
@daniel1991zy was wondering if you've ever found a work around for this? In my case, I'm my model structure has truncated chains compared to the native structure so I'm assuming this is causing the issue.

**Comment by teemuronkko** [comment]
@daniel1991zy @hyeh20 I also had this issue but like @hyeh20, my model structure also has truncated chains. Did either of you manage to solve it?

**Comment by hyeh20** [comment]
@teemuronkko my work-around solution was just to truncate the native to the same length as my model structure.
