### ISSUE TITLE
DockQ for the evaluation of protein-peptide complex predictions

### ISSUE THREAD

**Issue by nachotu** [bjornwallner/DockQ#54]
Hi,
DockQ can be used for the evaluation of protein-peptide complex predictions? I should consider peptide ligands as "small molecules"? What does "--capri_peptide" means?
Thank you for your help!

**Comment by clami66** [comment]
Hi, you can use DockQ for protein-peptide complexes. The `--capri_peptide` is useful to get a DockQ score more in line with the CAPRI community guidelines (see Table 3 [here](https://onlinelibrary.wiley.com/doi/10.1002/prot.25870)).

A peptide is not a small molecule, so you should not use that flag
