### ISSUE TITLE
Readme:./DockQ.py <model> <native>

### ISSUE THREAD

**Issue by Kaixiang-Wang** [bjornwallner/DockQ#6]
I want to predict the docking scores of the result of Alphafold-Multimer by DockQ. However, I have no idea which file is "model" and which one is "native".

**Comment by nemo8130** [comment]
'model' refers to the docked 'A-B' pose while 'native' is the native 'A-B' complex, solved experimentally. DockQ assesses the quality of the docked complex compared to its native reference.

**Comment by Kaixiang-Wang** [comment]
Thank you so much , so that DockQ can not predict the protein-protein docking scores which is not solved by experiment. Am I right?

**Comment by nemo8130** [comment]
Yes, for that you need a protein-protein docking scoring function (you may try: ProQDock which is trained on DockQ: https://academic.oup.com/bioinformatics/article/32/12/i262/2288786). DockQ is instead a 'quality measure'.

**Comment by Kaixiang-Wang** [comment]
Your advice is of great help to me and I will try it as soon as possible.

**Comment by nemo8130** [comment]
You are welcome. The ProQDock github package is available here: https://github.com/bjornwallner/ProQDock

**Comment by Kaixiang-Wang** [comment]
When I go to page ProQDock, I find the 'model.pdb' in example file is a two different protein heteromer (two different protein interact) but in the 'fulllength.fasta', there is only one protein sequence. Whether all the heteromer we need to get sequence with 'ProQDock/EXEC/pdb2fasta.pl' or I can input two protein sequence in the same fasta file to the program.

**Comment by nemo8130** [comment]
For these details please refer to the corresponding author of the paper (Prof. Bjorn Wallner) who updates and maintains the package eversince my post doctoral tenure was over in that lab. Though, for this particular query, 
![Screenshot from 2022-01-05 19-18-44](https://user-images.githubusercontent.com/10028565/148228718-a59141fd-116e-41ac-adf1-ff29e58f75a2.png)
I believe it is made quite clear in the [instructions](https://github.com/bjornwallner/ProQDock).

**Comment by Kaixiang-Wang** [comment]
yes, thank you so much.
