### ISSUE TITLE
Multichain functionality in readme 

### ISSUE THREAD

**Issue by chaotify3317** [bjornwallner/DockQ#8]
I try to run the readme example for multichain functionality and I get this.

Traceback (most recent call last):
  File "./DockQ.py", line 731, in <module>
    main()
  File "./DockQ.py", line 568, in main
    native=make_two_chain_pdb_perm(native,nat_group1,nat_group2)
  File "./DockQ.py", line 452, in make_two_chain_pdb_perm
    exec_path=os.path.dirname(Path.abspath(sys.argv[0]))
AttributeError: type object 'Path' has no attribute 'abspath'

**Comment by chaotify3317** [comment]
I got the readme example to work--- except when I try to use my own file it says "no such file or directory."

**Comment by kristianwant** [comment]
> 

Hi, what did you change from your previous comment to get the readme example to work? I'm struggling with the same issue.

**Comment by chaotify3317** [comment]
I deleted all the extra DockQ files I had, updated ubuntu(my terminal), then installed "sudo apt install emboss" on ubuntu. Atleast that's how I got it to work.
