### ISSUE TITLE
PermissionError: [WinError 32]

### ISSUE THREAD

**Issue by kristianwant** [bjornwallner/DockQ#9]
When i try to follow the example steps to check the installation is ok, the text file 'renumber_pdb' is just popping up on my screen.

I'm not sure why this popping up, and the program isn't running. Any help would be appreciated.
(I'm trying to run the software on windows, in the Anaconda terminal)

**Comment by kristianwant** [comment]
Update: I just hadn't assigned the renumber_pdb.pl filetype to perl, so when run it was opening the text file as default. This is now fixed. The issue I'm now getting is:

PermissionError: [WinError 32] The process cannot access the file because this file is in use by another process: 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\tmpkbs1gkir'

**Comment by kristianwant** [comment]
Update: I just hadn't assigned the renumber_pdb.pl filetype to perl, so when run it was opening the text file as default. This is now fixed. The issue I'm now getting is:

Traceback (most recent call last):
File "C:\Users\xxxx\Documents\ComputationalWork\Scripts\DockQ-1.0\DockQ.py", line 730, in
main()
File "C:\Users\xxxx\Documents\ComputationalWork\Scripts\DockQ-1.0\DockQ.py", line 567, in main
native=make_two_chain_pdb_perm(native,nat_group1,nat_group2)
File "C:\Users\xxxx\Documents\ComputationalWork\Scripts\DockQ-1.0\DockQ.py", line 454, in make_two_chain_pdb_perm
os.remove(outfile)

PermissionError: [WinError 32] The process cannot access the file because this file is in use by another process: 'C:\Users\xxxx\AppData\Local\Temp\tmpkbs1gkir'

**Comment by chaotify3317** [comment]
I also ran into this issue, what I originally did was try installing the tmp package, but that didn't work. So I just deleted all the DockQ files I had, ran an Ubuntu update, and reinstalled DockQ
